export { DashboardPage } from './DashboardPage';
export { ReceivingPage } from './ReceivingPage';
export { ReceivingSessionPage } from './ReceivingSessionPage';
export { StockPage } from './StockPage';
export { OpeningStockPage } from './OpeningStockPage';
export { OrdersAuditPage } from './OrdersAuditPage';
export { OrdersStockPage } from './OrdersStockPage';
export { OrdersInboxPage } from './OrdersInboxPage';
export { StockSettingsPage } from './StockSettingsPage';
export { SuppliersPage } from './SuppliersPage';
export { SupplierCatalogPage } from './SupplierCatalogPage';
export { InvoicesPage } from './InvoicesPage';
export { InvoiceDetailPage } from './InvoiceDetailPage';
export { ProductsPage, ShopsPage, SettingsPage } from './PlaceholderPages';
export { ProductDetailPage } from './ProductDetailPage';
