export const fifoCopy = {
  sk: {
    title: 'FIFO a skladové pohyby', warehouse: 'Sklad', chooseWarehouse: 'Vyberte sklad', loading: 'Načítavam…', refresh: 'Obnoviť',
    legacyCost: 'Pôvodná cena',
    legacy: 'Tento zostatok používa pôvodné priemerné ocenenie. FIFO zapnete po overení vrstiev pri prechode.',
    missing: 'Zatiaľ nie je evidovaný skladový zostatok. Prvý potvrdený príjem začne FIFO.',
    complete: 'Ocenenie je úplné', incomplete: 'Ocenenie je neúplné', unknown: 'Neznáma', provisional: 'Predbežná', known: 'Doložená',
    physical: 'Fyzicky', reserved: 'Rezervované', quarantine: 'Karanténa', available: 'Voľné na predaj',
    knownValue: 'Doložená hodnota', provisionalValue: 'Predbežná hodnota', unknownQty: 'Kusy bez ceny', avg: 'Priemerná cena zostávajúcich kusov',
    prices: 'Nákupné ceny v EUR bez DPH. Predbežné ceny nie sú konečné ocenenie.', layers: 'Príjmové vrstvy', history: 'Pohyby a výdaje',
    date: 'Fyzický príjem', quantity: 'Množstvo', remaining: 'Zostáva', cost: 'Cena za kus', state: 'Stav', source: 'Doklad / zdroj',
    next: 'Ďalší výdaj', last: 'Posledný príjem', noLayers: 'Žiadne FIFO vrstvy', previous: 'Predchádzajúce', following: 'Ďalšie',
    receive: 'Nový príjem', cutover: 'Prechod na FIFO', revise: 'Doplniť / opraviť cenu', release: 'Uvoľniť z karantény', return: 'Oficiálna vratka',
    cancel: 'Zavrieť formulár', operator: 'Zaevidoval', reason: 'Dôvod', case: 'Číslo vratky / reklamácie / neprevzatia',
    good: 'Bez poškodenia', damaged: 'Poškodený', condition: 'Stav vráteného tovaru', target: 'Cieľový sklad',
    addLayer: 'Pridať vrstvu', remove: 'Odobrať vrstvu', counted: 'Dátum overenia zostatku',
    cutoverHelp: 'Rozdeľte celý aktuálny zostatok podľa doložených príjmov. Neznámu cenu nechajte neznámu. Prechod nemení staré pohyby ani minulé výdaje.',
    receiveHelp: 'Použite iba pre skutočne prevzatý tovar. Príjem už zaevidovaný cez faktúru znova nepridávajte.',
    returnHelp: 'Tovar sa prijme do karantény za cenu pôvodného výdaja. Finančné vrátenie platby sa týmto neeviduje.',
    reviseHelp: 'Oprava precení zostávajúce vrstvy aj aktuálny čistý náklad výdajov. Pôvodné ceny pohybov ostanú zachované.',
    releaseHelp: 'Uvoľnite len skontrolovaný nepoškodený tovar. Dátum a pôvod nákupnej vrstvy sa zachovajú.',
    confirmed: 'Overil som údaje, fyzické množstvo a uvedený doklad. Pri vratke potvrdzujem skutočné prevzatie; pri uvoľnení kontrolu stavu.',
    preview: 'Skontrolovať náhľad', apply: 'Potvrdiť zápis', retry: 'Overiť / zopakovať rovnaký zápis',
    previewHelp: 'Skontrolujte množstvá, ceny a doklady. Zápis sa vykoná až potvrdením.',
    saved: 'Skladový zápis bol uložený.', failed: 'Zápis sa nepodarilo potvrdiť. Obnovte údaje alebo zopakujte rovnakú požiadavku.',
    readFailed: 'Údaje sa nepodarilo načítať.', validation: 'Vyplňte doklad, dôvod a platné množstvo alebo cenu. Potvrďte kontrolu údajov.',
    pending: 'Výsledok posledného zápisu ešte nie je potvrdený. Opakujte rovnakú požiadavku; nový zápis zatiaľ nezačínajte.',
    issue: 'Výdaj', returned: 'Už vrátené', returnable: 'Možno vrátiť', allocation: 'Rozpis FIFO výdaja', originalCost: 'Cena pri výdaji', currentCost: 'Aktuálna cena',
    netCost: 'Aktuálny čistý náklad', revisions: 'Opravy ceny', noMovements: 'Žiadne skladové pohyby', inspect: 'Rozpis / vratka',
    notMargin: 'Náklad výdaja nie je marža. Marža vyžaduje overenú tržbu bez DPH, zľavy a prípadné refundácie.',
  },
  en: {
    title: 'FIFO and stock movements', warehouse: 'Warehouse', chooseWarehouse: 'Select warehouse', loading: 'Loading…', refresh: 'Refresh',
    legacyCost: 'Legacy cost',
    legacy: 'This balance uses the previous average valuation. Enable FIFO after verifying its opening layers.',
    missing: 'No stock balance is recorded yet. The first confirmed receipt starts FIFO.',
    complete: 'Valuation is complete', incomplete: 'Valuation is incomplete', unknown: 'Unknown', provisional: 'Provisional', known: 'Documented',
    physical: 'Physical', reserved: 'Reserved', quarantine: 'Quarantine', available: 'Available for sale',
    knownValue: 'Documented value', provisionalValue: 'Provisional value', unknownQty: 'Units without cost', avg: 'Average remaining unit cost',
    prices: 'Acquisition costs in EUR excluding VAT. Provisional costs are not final valuation.', layers: 'Receipt layers', history: 'Movements and issues',
    date: 'Physical receipt', quantity: 'Quantity', remaining: 'Remaining', cost: 'Unit cost', state: 'Status', source: 'Document / source',
    next: 'Next issue', last: 'Latest receipt', noLayers: 'No FIFO layers', previous: 'Previous', following: 'Next',
    receive: 'New receipt', cutover: 'Switch to FIFO', revise: 'Add / correct cost', release: 'Release quarantine', return: 'Official return',
    cancel: 'Close form', operator: 'Recorded by', reason: 'Reason', case: 'Return / claim / non-collection reference',
    good: 'Undamaged', damaged: 'Damaged', condition: 'Returned item condition', target: 'Target warehouse',
    addLayer: 'Add layer', remove: 'Remove layer', counted: 'Balance verification date',
    cutoverHelp: 'Account for the entire current balance with documented receipt layers. Keep missing cost unknown. Cutover does not change old movements or past issues.',
    receiveHelp: 'Use only for goods physically received. Do not add a receipt already recorded from an invoice.',
    returnHelp: 'Goods enter quarantine at their original issue cost. This does not record a financial refund.',
    reviseHelp: 'The correction revalues remaining layers and current net issue costs. Original movement costs remain unchanged.',
    releaseHelp: 'Release only checked undamaged goods. Receipt date and cost provenance are preserved.',
    confirmed: 'I checked the data, physical quantity and document. For returns I confirm physical receipt; for release I confirm the condition check.',
    preview: 'Review preview', apply: 'Confirm entry', retry: 'Verify / retry the same entry',
    previewHelp: 'Check quantities, costs and documents. The entry takes effect only after confirmation.',
    saved: 'Stock entry saved.', failed: 'The entry could not be confirmed. Refresh the data or retry the same request.',
    readFailed: 'Could not load the data.', validation: 'Enter a document, reason and valid quantity or cost, and confirm the checks.',
    pending: 'The previous entry is not confirmed yet. Retry the same request before starting another entry.',
    issue: 'Issue', returned: 'Already returned', returnable: 'Returnable', allocation: 'FIFO issue breakdown', originalCost: 'Cost at issue', currentCost: 'Current cost',
    netCost: 'Current net cost', revisions: 'Cost corrections', noMovements: 'No stock movements', inspect: 'Breakdown / return',
    notMargin: 'Issue cost is not margin. Margin requires verified revenue excluding VAT, discounts and any refunds.',
  },
};

export const fifoErrors: Record<'sk' | 'en', Record<string, string>> = {
  sk: {
    fifo_preview_stale: 'Zásoba sa od náhľadu zmenila. Obnovte údaje a pripravte nový náhľad.',
    fifo_preview_expired: 'Náhľad vypršal. Pripravte nový náhľad.',
    fifo_cutover_required: 'Starší zostatok najprv preveďte na FIFO cez overené príjmové vrstvy.',
    fifo_cutover_quantity_mismatch: 'Súčet vrstiev musí byť presne rovnaký ako aktuálny fyzický zostatok.',
    fifo_date_invalid: 'Dátum príjmu nesmie byť v budúcnosti ani po dátume overenia zostatku.',
    fifo_return_legacy_issue_unsupported: 'Tento starší výdaj nemá doložené FIFO alokácie. Bežnú FIFO vratku preto nemožno vytvoriť.',
    fifo_return_fractional_allocation_unsupported: 'Výdaj obsahuje zlomky príjmových vrstiev. Táto verzia vratiek podporuje iba celé kusy v alokáciách.',
    fifo_return_quantity_exceeds_issue: 'Požadované množstvo prekračuje počet kusov, ktoré ešte možno vrátiť.',
    fifo_release_condition_not_good: 'Poškodený alebo neoverený tovar nemožno uvoľniť do predaja.',
    fifo_activation_required: 'Cieľový skladový zostatok najprv vyžaduje kontrolovaný prechod na FIFO.',
    fifo_cost_revision_conflict: 'Nákupnú cenu medzitým zmenil iný používateľ. Obnovte detail ceny.',
    fifo_invalid_request: 'Skontrolujte množstvo, cenu, doklady a povinné potvrdenia.',
    stock_publication_warehouse_held: 'Sklad je blokovaný pre prebiehajúcu údržbu synchronizácie. Dokončite ju pred skladovým zápisom.',
  },
  en: {
    fifo_preview_stale: 'Stock changed after the preview. Refresh and prepare a new preview.',
    fifo_preview_expired: 'The preview expired. Prepare a new preview.',
    fifo_cutover_required: 'First switch the legacy balance to FIFO using verified receipt layers.',
    fifo_cutover_quantity_mismatch: 'Layer quantities must add up exactly to the current physical balance.',
    fifo_date_invalid: 'Receipt dates cannot be in the future or after the balance verification date.',
    fifo_return_legacy_issue_unsupported: 'This legacy issue has no documented FIFO allocations, so a regular FIFO return is unavailable.',
    fifo_return_fractional_allocation_unsupported: 'The issue contains fractional layer allocations. This return version supports whole pieces in each allocation.',
    fifo_return_quantity_exceeds_issue: 'The requested quantity exceeds the units still eligible for return.',
    fifo_release_condition_not_good: 'Damaged or unchecked goods cannot be released for sale.',
    fifo_activation_required: 'The destination stock balance requires a documented FIFO cutover first.',
    fifo_cost_revision_conflict: 'Another operator changed the cost. Refresh its detail before continuing.',
    fifo_invalid_request: 'Check quantities, costs, documents and required confirmations.',
    stock_publication_warehouse_held: 'The warehouse is held for stock synchronization maintenance. Complete it before recording stock changes.',
  },
};
